### ISSUE TITLE
503 Error when visiting custom domain

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/launchdock#25]
I finally got around to setting up a custom domain w/ (self signed) SSL certs on my PAAS hosted reactioncommerce.com site

It appears that the server is configured correctly because I received the Chrome warning about an untrusted SSL cert, but after 'proceeding anyway' I was greeted with a 503 error.

![image](https://cloud.githubusercontent.com/assets/1203639/12930997/c445b8c6-cf38-11e5-9b32-5b63f9c5be1b.png)

I've got my CNAME pointed as requested in the LaunchDock dashboard 

This is what my `/dashboard/connect' domain looks like, and it appears that the SSL key and cert were saved and are being used
![image](https://cloud.githubusercontent.com/assets/1203639/12931060/14e82dc2-cf39-11e5-898e-d11cfaefe558.png)

I just added the key and cert about 5 minutes ago, so it's possible that it just takes a little while (server restart?) for it to take affect, but the CNAME record seems to have taken effect already.

<img width="410" alt="screen shot 2016-02-09 at 2 54 08 pm" src="https://cloud.githubusercontent.com/assets/1203639/12931952/8a466760-cf3d-11e5-8892-d04cdc8bfe46.png">

**Comment by spencern** [comment]
After looking for more details, it doesn't appear that my self-signed cert is being used at all.

![image](https://cloud.githubusercontent.com/assets/1203639/12932790/e2e9d97a-cf41-11e5-90da-6837437eed72.png)

**Comment by spencern** [comment]
Should I have listed this issue under github.com/reactioncommerce/launchdock-connect instead? It seems like it's somewhat related to https://github.com/reactioncommerce/launchdock-connect/issues/6

**Comment by spencern** [comment]
The domain problem seems to be fixed now, not sure if there were changes made or if it just took more time than expected.

The certificate is still the reactioncommerce.com wildcard cert and doesn't match the custom domain.

**Comment by aaronjudd** [comment]
That issue is more UI/process related I think, while this was a breakdown in the implementation. @jshimko is on this, while I had good intentions of updating the UI ;-)

**Comment by jshimko** [comment]
Hey @spencern, thanks for reporting all of this!

I ended up having to go down a bit of a rabbit hole while trying to sort this stuff out, but I deployed a bunch of updates a few hours ago and I think it should all finally be working for you now.  I haven't tried a self-signed certificate, but I've tested extensively with purchased certificates and it has been working well for me.  

We're working on making the experience a little clearer from the UI perspective, but the process essentially goes like this...

You submit your domain and certificate and they get inserted into your shop deployment as environment variables.  The app is then quickly restarted (usually within 15-30 seconds) and once it's done, you should see the page automatically refresh.  Once that happens, your custom domain should be working (assuming you've pointed it at the specified endpoint).

You'll always see the `*.reactioncommerce.com` certificate when no matching certificate is found because that's the fallback wildcard.  But if you submit a valid certificate that matches the domain you specify, you should be able to use both your custom domain and the subdomain that you're given when your shop is created.

So just so I'm clear, are you saying it _is_ working for you now?

**Comment by spencern** [comment]
Hey @jshimko,

Thanks for looking into this.

When I first opened this issue, I was receiving a 503 error anytime I visited the custom domain.
That issue appears to have been fixed.

There is a second issue, which I can open a new github issue for if you like, where my SSL certificate for the custom domain doesn't appear to be loading. This is a self-created and self-signed certificate, but I've used similar certificates on other hosts with no problem (other than browsers throwing a warning).

I just re-copied the `.crt` and `.key` into my launchdock-connect dashboard and 3 minutes later am still seeing the fallback `*.reactioncommerce.com` certificate

![image](https://cloud.githubusercontent.com/assets/1203639/13000330/57ffdcde-d116-11e5-8bf8-1b8bb9267d33.png)

When I clicked 'Save Settings' this time, I did get a green 'success' bootstrap alert confirming that the system was talking with launchdock, but have not seen my certificate load yet.

**Comment by jshimko** [comment]
Hey @spencern, looks like you might not have set up your self-signed certificate correctly.  It worked for me...

![getoutfitted-ssl](https://cloud.githubusercontent.com/assets/3077956/13010702/2b09bc9e-d171-11e5-878a-d7bb24e9eb19.jpg)

Are you specifying the FQDN when generating the CSR?  The cert definitely needs to specify your exact domain or the load balancer won't know to present it to the browser and will fall back to our `*.reactioncommerce.com` wildcard.

**Comment by spencern** [comment]
@jshimko I regenerated my cert and it seems like the cert is working now.

However, the 503 error is back. I updated the server about an hour ago and now the cert is showing correctly, but I can't load the app.

![image](https://cloud.githubusercontent.com/assets/1203639/13018553/68620ce8-d187-11e5-81be-763b3e01a4e7.png)

**Comment by jshimko** [comment]
It looks like it maybe got stuck while restarting.  It appears to be working now...

![go-ssl](https://cloud.githubusercontent.com/assets/3077956/13018719/417af574-d199-11e5-9597-3ad46f0789eb.jpg)

**Comment by spencern** [comment]
Yep, appears to be working now. Thanks for the help. Closing
